services:
  postgres:
    image: postgres:latest
    container_name: {{cookiecutter.container_name}}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - {{cookiecutter.volumes}}:/var/lib/postgresql/data

volumes:
  {{cookiecutter.volumes}}:
